// MathJax Configuration
window.MathJax = {
  tex: {
    inlineMath: [['$', '$'], ['\\(', '\\)']],
    displayMath: [['$$', '$$'], ['\\[', '\\]']]
  },
  svg: { fontCache: 'global' }
};

// Load MathJax asynchronously
(function loadMathJax() {
  const script = document.createElement('script');
  script.src = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js';
  script.async = true;
  document.head.appendChild(script);
})();

(async function main() {
  const feedUrls = ['http://rss.arxiv.org/rss/math.RA/'];
  const proxyBase = 'https://api.rss2json.com/v1/api.json?rss_url=';
  const feedContainer = document.getElementById('feed');

  try {
    // 1. Fetch live feeds for the default view
    const responses = await Promise.all(
      feedUrls.map(url => fetch(proxyBase + encodeURIComponent(url)).then(res => res.json()))
    );
    
    let liveItems = responses.flatMap((data, i) => 
      (data.status === 'ok' && Array.isArray(data.items))
        ? data.items.map(item => ({ ...item, __source: feedUrls[i] }))
        : []
    ).sort((a, b) => new Date(b.pubDate) - new Date(a.pubDate));

    if (!liveItems.length) {
      feedContainer.innerHTML = '<p>No items could be loaded from any feed.</p>';
      return;
    }

    // Render live items initially
    renderItems(liveItems, feedContainer);

    // 2. Setup Archive Button Logic
    const navContainer = document.querySelector('.navbar .container');
    if (navContainer) {
      const archiveBtn = document.createElement('a');
      archiveBtn.href = '#';
      archiveBtn.className = 'navbar-brand'; 
      archiveBtn.textContent = ' [Archive]';
      navContainer.appendChild(archiveBtn);

      let isArchiveView = false;
      let archiveItems = null; 

      archiveBtn.addEventListener('click', async (e) => {
        e.preventDefault();
        isArchiveView = !isArchiveView;
        archiveBtn.textContent = isArchiveView ? ' [Back to Feed]' : ' [Archive]';
        
        feedContainer.innerHTML = ''; 
        
        if (isArchiveView) {
          // --- NEW: Inject Date Picker UI ---
          feedContainer.innerHTML = `
            <div style="margin-bottom: 20px; display: flex; gap: 10px; align-items: center; padding: 10px; background: #f8f9fa; border-radius: 5px;">
              <label for="archive-date" style="font-weight: bold;">Filter by Date:</label>
              <input type="date" id="archive-date" style="padding: 5px; border: 1px solid #ccc; border-radius: 4px;">
              <button id="clear-date" style="padding: 5px 10px; cursor: pointer; border: 1px solid #ccc; background: white; border-radius: 4px;">Clear Filter</button>
            </div>
            <div id="archive-content"></div>
          `;
          
          const contentContainer = document.getElementById('archive-content');
          const dateInput = document.getElementById('archive-date');
          const clearBtn = document.getElementById('clear-date');

          // Fetch the static archive.json generated by GitHub Actions
          if (!archiveItems) {
            contentContainer.innerHTML = '<p>Loading archive...</p>';
            try {
              const res = await fetch('./archive.json');
              archiveItems = await res.json();
            } catch (err) {
              console.error("Could not load archive:", err);
              archiveItems = liveItems; 
            }
          }
          
          // Initial render of all archive items
          renderItems(archiveItems, contentContainer);

          // --- NEW: Filter Logic ---
          dateInput.addEventListener('change', (event) => {
            const selectedDate = event.target.value; // Format: YYYY-MM-DD
            if (!selectedDate) {
              return renderItems(archiveItems, contentContainer);
            }

            const filteredItems = archiveItems.filter(item => {
              // Extract just the YYYY-MM-DD part from the item's publication date
              const itemDate = new Date(item.pubDate).toISOString().split('T')[0];
              return itemDate === selectedDate;
            });

            if (filteredItems.length === 0) {
              contentContainer.innerHTML = '<p>No articles found for this date.</p>';
            } else {
              renderItems(filteredItems, contentContainer);
            }
          });

          // Clear button logic
          clearBtn.addEventListener('click', () => {
            dateInput.value = '';
            renderItems(archiveItems, contentContainer);
          });

        } else {
          // Show live feeds
          renderItems(liveItems, feedContainer);
        }
      });
    }

  } catch (error) {
    feedContainer.innerHTML = `<p style="color:red">Error loading feeds: ${error.message}</p>`;
    console.error('Feed fetch error:', error);
  }
})();

// Helper function to render items and trigger MathJax
function renderItems(items, container) {
  container.innerHTML = ''; // Clear container before rendering
  const fragment = document.createDocumentFragment();
  items.forEach(item => {
    const article = document.createElement('article');
    article.className = 'card mb-4';
    article.innerHTML = `
      <header class="card-header">
        <h2 class="card-title">
          <a href="${item.link}" target="_blank" rel="noopener noreferrer">${item.title}</a>
        </h2>
        <time class="card-meta">${new Date(item.pubDate).toLocaleString()}</time>
      </header>
      <div class="card-body">
        <p>${item.contentSnippet || ''}</p>
      </div>
      <footer class="card-footer">
        <small>Source: <a href="${item.__source}" target="_blank" rel="noopener noreferrer">${new URL(item.__source).hostname}</a></small>
      </footer>
    `;
    fragment.appendChild(article);
  });
  container.appendChild(fragment);
  if (window.MathJax?.typesetPromise) {
    window.MathJax.typesetPromise().catch(err => console.error(err));
  }
}
