// MathJax Configuration
window.MathJax = {
  tex: {
    inlineMath: [['$', '$'], ['\\(', '\\)']],
    displayMath: [['$$', '$$'], ['\\[', '\\]']]
  },
  svg: { fontCache: 'global' }
};

// Load MathJax asynchronously
(function loadMathJax() {
  const script = document.createElement('script');
  script.src = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js';
  script.async = true;
  document.head.appendChild(script);
})();

// Inject date input styling dynamically so we don't have to touch style.css
(function injectDateStyles() {
  if (!document.getElementById('date-input-style')) {
    const style = document.createElement('style');
    style.id = 'date-input-style';
    style.textContent = `
      input[type="date"] {
          color: var(--input-color);
          background: var(--input-background);
          border: var(--input-border);
          padding: 3px;
          line-height: 20px;
          width: 250px;
          font-size: 99%;
          margin-top: 5px;
          appearance: none;
      }
      input[type="date"]:focus {
          color: var(--input-focus-color);
          border-color: var(--input-focus-border-color);
          outline: 0;
          box-shadow: var(--input-focus-box-shadow);
      }
    `;
    document.head.appendChild(style);
  }
})();

(async function main() {
  const feedUrls = ['http://rss.arxiv.org/rss/math.RA/'];
  const proxyBase = 'https://api.rss2json.com/v1/api.json?rss_url=';
  const feedContainer = document.getElementById('feed');

  try {
    // 1. Fetch live feeds for the default view
    const responses = await Promise.all(
      feedUrls.map(url => fetch(proxyBase + encodeURIComponent(url)).then(res => res.json()))
    );
    
    let liveItems = responses.flatMap((data, i) => 
      (data.status === 'ok' && Array.isArray(data.items))
        ? data.items.map(item => ({ ...item, __source: feedUrls[i] }))
        : []
    ).sort((a, b) => new Date(b.pubDate) - new Date(a.pubDate));

    if (liveItems.length) {
      renderItems(liveItems, feedContainer);
    }

    // --- FIX: Make "0ch" Logo redirect home ---
    const logoBtn = document.querySelector('.navbar .container .navbar-brand');
    if (logoBtn) {
      logoBtn.addEventListener('click', (e) => {
        e.preventDefault();
        window.location.reload(); 
      });
    }

    // 2. Setup Archive Button Logic
    const navContainer = document.querySelector('.navbar .container');
    if (navContainer) {
      const archiveBtn = document.createElement('a');
      archiveBtn.href = '#';
      archiveBtn.className = 'navbar-brand'; 
      archiveBtn.textContent = ' [Archive]';
      navContainer.appendChild(archiveBtn);

      let isArchiveView = false;
      let archiveItems = null; 

      archiveBtn.addEventListener('click', async (e) => {
        e.preventDefault();
        isArchiveView = !isArchiveView;
        archiveBtn.textContent = isArchiveView ? ' [Back to Feed]' : ' [Archive]';
        
        feedContainer.innerHTML = ''; 
        
        if (isArchiveView) {
          // Used native CSS elements (fieldset, legend, .button) for styling
          feedContainer.innerHTML = `
            <fieldset>
              <legend>Filter by Date</legend>
              <div class="form-label-row" style="align-items: center; gap: 15px;">
                <input type="date" id="archive-date">
                <button id="clear-date" class="button">Clear Filter</button>
              </div>
            </fieldset>
            <div id="archive-content"></div>
          `;
          
          const contentContainer = document.getElementById('archive-content');
          const dateInput = document.getElementById('archive-date');
          const clearBtn = document.getElementById('clear-date');

          // Fetch the static archive.json generated by GitHub Actions
          if (!archiveItems) {
            contentContainer.innerHTML = '<p>Loading archive...</p>';
            try {
              const res = await fetch('./archive.json');
              archiveItems = await res.json();
            } catch (err) {
              console.error("Could not load archive:", err);
              archiveItems = []; 
            }
          }
          
          // Initial render of all archive items
          renderItems(archiveItems, contentContainer);

          // Filter Logic
          dateInput.addEventListener('change', (event) => {
            const selectedDate = event.target.value; 
            if (!selectedDate) {
              return renderItems(archiveItems, contentContainer);
            }

            const filteredItems = archiveItems.filter(item => {
              const itemDate = new Date(item.pubDate).toISOString().split('T')[0];
              return itemDate === selectedDate;
            });

            if (filteredItems.length > 0) {
              renderItems(filteredItems, contentContainer);
            } else {
              contentContainer.innerHTML = '<p>No items found for this date.</p>';
            }
          });

          // Clear button logic
          clearBtn.addEventListener('click', () => {
            dateInput.value = '';
            renderItems(archiveItems, contentContainer);
          });

        } else {
          // Show live feeds
          renderItems(liveItems, feedContainer);
        }
      });
    }

  } catch (error) {
    feedContainer.innerHTML = `<p style="color:red">Error loading feeds: ${error.message}</p>`;
    console.error('Feed fetch error:', error);
  }
})();

// Helper function to render items and trigger MathJax
function renderItems(items, container) {
  container.innerHTML = ''; 
  const fragment = document.createDocumentFragment();
  
  const dateOptions = { 
    year: 'numeric', 
    month: 'short', 
    day: 'numeric', 
    hour: '2-digit', 
    minute: '2-digit' 
  };

  items.forEach(item => {
    const article = document.createElement('article');
    article.className = 'card mb-4';

    const authorLinks = item.author
      ? item.author.split(',').map(name => {
          const trimmed = name.trim();
          const query = encodeURIComponent(trimmed);
          return `<a href="https://arxiv.org/search/?query=${query}&searchtype=author" target="_blank" rel="noopener noreferrer">${trimmed}</a>`;
        }).join(', ')
      : '';
      
    const subjects = Array.isArray(item.categories) && item.categories.length
      ? item.categories.join(', ')
      : '';

    // Extract and format the date
    const pubDate = item.pubDate ? new Date(item.pubDate).toLocaleDateString(undefined, dateOptions) : '';

    article.innerHTML = `
      <header class="card-header">
        <h2 class="card-title">
          <a href="${item.link}" target="_blank" rel="noopener noreferrer">${item.title}</a>
        </h2>
        ${authorLinks ? `<span class="card-meta">${authorLinks}</span>` : ''}
        ${pubDate ? `<div class="entry-date" style="margin-top: 5px;">${pubDate}</div>` : ''}
      </header>
      <div class="card-body">
        <p>${item.contentSnippet || ''}</p>
      </div>
      ${subjects ? `<footer class="card-footer">
        <small><strong>Subjects:</strong> ${subjects}</small>
      </footer>` : ''}
    `;
    fragment.appendChild(article);
  });
  container.appendChild(fragment);
  if (window.MathJax?.typesetPromise) {
    window.MathJax.typesetPromise().catch(err => console.error(err));
  }
}
