// MathJax Configuration
window.MathJax = {
  tex: {
    inlineMath: [['$', '$'], ['\\(', '\\)']],
    displayMath: [['$$', '$$'], ['\\[', '\\]']]
  },
  svg: { fontCache: 'global' }
};

// Load MathJax asynchronously
(function loadMathJax() {
  const script = document.createElement('script');
  script.src = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js';
  script.async = true;
  document.head.appendChild(script);
})();

(async function main() {
  const feedUrls = ['http://rss.arxiv.org/rss/math.RA/'];
  const proxyBase = 'https://api.rss2json.com/v1/api.json?rss_url=';
  const feedContainer = document.getElementById('feed');

  try {
    // 1. Fetch live feeds for the default view
    const responses = await Promise.all(
      feedUrls.map(url => fetch(proxyBase + encodeURIComponent(url)).then(res => res.json()))
    );
    
    let liveItems = responses.flatMap((data, i) => 
      (data.status === 'ok' && Array.isArray(data.items))
        ? data.items.map(item => ({ ...item, __source: feedUrls[i] }))
        : []
    ).sort((a, b) => new Date(b.pubDate) - new Date(a.pubDate));

    if (!liveItems.length) {
      feedContainer.innerHTML = '<p>No items could be loaded from any feed.</p>';
      return;
    }

    // Render live items initially
    renderItems(liveItems, feedContainer);

    // 2. Setup Archive Button Logic
    const navContainer = document.querySelector('.navbar .container');
    if (navContainer) {
      const archiveBtn = document.createElement('a');
      archiveBtn.href = '#';
      archiveBtn.className = 'navbar-brand'; 
      archiveBtn.textContent = ' [Archive]';
      navContainer.appendChild(archiveBtn);

      let isArchiveView = false;
      let archiveItems = null; // We will fetch this only if the user clicks the button

      archiveBtn.addEventListener('click', async (e) => {
        e.preventDefault();
        isArchiveView = !isArchiveView;
        archiveBtn.textContent = isArchiveView ? ' [Back to Feed]' : ' [Archive]';
        
        // Clear the feed container completely without adding any header text
        feedContainer.innerHTML = ''; 
        
        if (isArchiveView) {
          // Fetch the static archive.json generated by GitHub Actions
          if (!archiveItems) {
            try {
              const res = await fetch('./archive.json');
              archiveItems = await res.json();
            } catch (err) {
              console.error("Could not load archive:", err);
              archiveItems = liveItems; // Fallback to live items if archive fails
            }
          }
          renderItems(archiveItems, feedContainer);
        } else {
          // Show live feeds
          renderItems(liveItems, feedContainer);
        }
      });
    }

  } catch (error) {
    feedContainer.innerHTML = `<p style="color:red">Error loading feeds: ${error.message}</p>`;
    console.error('Feed fetch error:', error);
  }
})();

// Helper function to render items and trigger MathJax
function renderItems(items, container) {
  const fragment = document.createDocumentFragment();
  items.forEach(item => {
    const article = document.createElement('article');
    article.className = 'card mb-4';
    article.innerHTML = `
      <header class="card-header">
        <h2 class="card-title">
          <a href="${item.link}" target="_blank" rel="noopener noreferrer">${item.title}</a>
        </h2>
        <time class="card-meta">${new Date(item.pubDate).toLocaleString()}</time>
      </header>
      <div class="card-body">
        <p>${item.contentSnippet || ''}</p>
      </div>
      <footer class="card-footer">
        <small>Source: <a href="${item.__source}" target="_blank" rel="noopener noreferrer">${new URL(item.__source).hostname}</a></small>
      </footer>
    `;
    fragment.appendChild(article);
  });
  container.appendChild(fragment);
  if (window.MathJax?.typesetPromise) {
    window.MathJax.typesetPromise().catch(err => console.error(err));
  }
}
